package main

var ValidExts = map[string]string{
	"adb":   "Ada",
	"aspx":  "ASPX",
	"awk":   "Awk",
	"bash":  "Bash",
	"bat":   "Batch",
	"c":     "C",
	"cpp":   "C++",
	"cs":    "C#",
	"css":   "CSS",
	"d":     "D",
	"erl":   "Erlang",
	"f":     "F",
	"fs":    "f#",
	"go":    "Go",
	"java":  "Java",
	"js":    "Javascript",
	"kt":    "Koltin",
	"lua":   "Lua",
	"m":     "Matlab",
	"php":   "PHP",
	"pl":    "Pearl",
	"py":    "Python",
	"rb":    "Ruby",
	"rs":    "Rust",
	"scala": "Scala",
	"sh":    "Shell",
	"sql":   "SQL",
	"swift": "Swift",
	"vb":    "Visual Basic",
	"vim":   "Vimscript",
}
