package main

var ValidExts = map[string]bool{
	"aspx":  true,
	"bash":  true,
	"bat":   true,
	"c":     true,
	"cpp":   true,
	"cs":    true,
	"css":   true,
	"d":     true,
	"erl":   true,
	"f":     true,
	"go":    true,
	"java":  true,
	"js":    true,
	"lua":   true,
	"php":   true,
	"pl":    true,
	"py":    true,
	"scala": true,
	"sh":    true,
	"swift": true,
	"vim":   true,
	"m":     true,
	"awk":   true,
	"fs":    true,
	"kt":    true,
}
